import '../styles/globals.scss';

export const metadata = {
    title: '로켓AI',
    // description: 'Generated by create n ext app',
    // icons: {
    //     icon: '/favicon.ico',
    // },
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}
